# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

# The version of the configuration file format.
version: "0.2"
# The locale to use when spell checking. (e.g., en, en-GB, de-DE
language: en
ignoreWords:
  - vitepress
  - APDC
  - ArduPilot
  - Ardu
  - Heathrow
  - Paddington
  - Teesside
  - Catterick
  - Kear
  - thetrainline
  - Tridgell
  - Mackay
  - Piaza
  - Aukland
  - Easby
  - FORNO
  - CARBONARA
  - pancetta
  - pois
  - MELENZANE
  - napoli
  - PANCIOTTI
  - FRUTTI
  - SALMONE
  - Arborio
  - VERDEA
  - TOSCANO
  - SEABASS
  - demi
  - POLLO
  - AGLIO
  - GAMBERONI
  - cotto
  - VEGETARIANA
  - GAMBERI
  - LAKSA
