name: Deploy Conf Wiki to cPanel

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Test all
        run: npm run test:all

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.CPANEL_FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .vitepress/dist/
          server-dir: ./
