name: Run CI on master branch

on:
  push:
    branches:
      - master

jobs:
  build-formmatting-spelling:
    runs-on: windows-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Test all
        run: npm run test:all
